name       : perl-libnet
version    : '3.11'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHAY/libnet-3.11.tar.gz : 2fab1e4d6e565c77f6e845368790de65cb2f966fcd9bb56a41d0e7b5851a52d3
license    : Artistic-Perl-1.0
summary    : |
    Perl Net:: namespace
component  : programming.perl
builddeps  :
    - perl-io
description: |
    Perl Net:: namespace
setup      : |
    # Stop prompts
    %perl_setup < /dev/null
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
