name       : perl-libnet
version    : '3.10'
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/S/SH/SHAY/libnet-3.10.tar.gz : 53bf4478301cf2377f04534c74ef116412dee8c726ae6245115c0ad11daa8061
license    : Artistic-Perl-1.0
summary    : |
    Perl Net:: namespace
component  : programming.perl
builddeps  :
    - perl
    - perl-io
    - perl-extutils-makemaker
description: |
    Perl Net:: namespace
setup      : |
    # Stop prompts
    %perl_setup < /dev/null
build      : |
    %perl_build
install    : |
    %perl_install
