name       : perl-libnet
version    : '3.15'
release    : 13
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHAY/libnet-3.15.tar.gz : a71f4db580e1a767d6936faa5baf38f1fa617824342da078b561283e86f8f4a2
homepage   : https://metacpan.org/dist/libnet
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Perl clients for various network protocols
description: |
    libnet is a collection of Perl modules which provides a simple and consistent programming interface (API) to the client side of various protocols used in the internet community.
builddeps  :
    - perl-io
setup      : |
    # Stop prompts
    %perl_setup < /dev/null
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
