name        : perl-libnet
version     : 3.08
release     : 4
source     :
    - http://search.cpan.org/CPAN/authors/id/S/SH/SHAY/libnet-3.08.tar.gz : 21ebae642b53336576c370989d238cbe74378944079aca6f97665158c9f1750b
license     :
    - Artistic-Perl-1.0
summary     : |
    Perl Net:: namespace
component   : programming.perl
builddeps   :
    - perl
    - perl-io
    - perl-extutils-makemaker
description : |
    Perl Net:: namespace
setup      : |
    # Stop prompts
    %perl_setup < /dev/null
build      : |
    %perl_build
install    : |
    %perl_install
