name       : perl-libnet
version    : '3.14'
release    : 12
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHAY/libnet-3.14.tar.gz : 153c8eb8ef0f19cf2c631d5b45d05de98516937f34e261125ef242fba1fe2ea4
homepage   : https://metacpan.org/dist/libnet
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Perl clients for various network protocols
description: |
    libnet is a collection of Perl modules which provides a simple and consistent programming interface (API) to the client side of various protocols used in the internet community.
builddeps  :
    - perl-io
setup      : |
    # Stop prompts
    %perl_setup < /dev/null
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
